### ISSUE TITLE
Ревью домашней работы по React

### ISSUE THREAD

**Issue by etozhenerk** [ZeraiGR/shri-react-hw-2023#2]
Привет! Делаю ревью твоей работы. Работа отличная, все пункты выполнены.
Ставлю 11 баллов.

Комментарии по проекту, которые не повлияли на оценку.
1. Билд не собирается, падает сборка [скрин](https://skr.sh/sKYotSzKveS).
Скорее всего проблема в этом экспорте https://github.com/ZeraiGR/shri-react-hw-2023/blob/d33ab69c0ffbdf61dd763b6b505a8376607491d3/src/app/page.tsx#L19.
2. Есть баги в адаптиве [скрин](https://skr.sh/sKYnkUuA4bp).
3. На странице фильма забыл добавить цвет фона для блоков [скрин](https://skr.sh/sKYBe0ZpwRl)
4. В сторе остались тестовые данные https://github.com/ZeraiGR/shri-react-hw-2023/blob/d33ab69c0ffbdf61dd763b6b505a8376607491d3/src/store/features/cartSlice.ts#L6-L9
5. Подобную логику я бы выносил в хуки. Если хук спецефичен для компонента, то обычно держу их рядом с компонентом. 
https://github.com/ZeraiGR/shri-react-hw-2023/blob/d33ab69c0ffbdf61dd763b6b505a8376607491d3/src/app/ui/ClientFilter/ClientFilter.tsx#L19-L34
https://github.com/ZeraiGR/shri-react-hw-2023/blob/d33ab69c0ffbdf61dd763b6b505a8376607491d3/src/app/ui/DropDown/DropDownList.tsx#L37-L67
6. Констаты ссылочного типа я бы мемоизировал, что бы они не дергались на каждый ререндер компонента https://github.com/ZeraiGR/shri-react-hw-2023/blob/d33ab69c0ffbdf61dd763b6b505a8376607491d3/src/app/ui/DropDown/DropDownList.tsx#L60-L67

**Comment by ZeraiGR** [comment]
Миша Привет, большое спасибо за ревью! Действительно многие моменты не учел, уже на полных скоростях заканчивал, недотестил местами, обязательно поправлю)

**Comment by ZeraiGR** [comment]
Ошибки пофиксил, рефакторинг провёл, недочёты устранил
